version: "1.0"
stages:
  - "clone"
  - "build"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "misssuellen/saleor"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "misssuellen/saleor"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
  deploy:
    title: "deploying to cluster"
    type: "deploy"
    stage: "deploy"
    arguments:
      kind: "kubernetes"
      cluster: "saleor"
      namespace: "store"
      service: "store-stack"